spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/majab
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

  jackson:
    time-zone: Asia/Seoul

management:
  endpoints:
    web:
      exposure:
        include: health